name: opengl-jp
channels:
  - defaults
  - conda-forge
  - open3d-admin
dependencies:
  - python=3.9
  - numpy
  - pyrr
  - glfw
  - PyOpenGL
  - pillow
  - scikit-learn
  - pip
  - pip:
      - addict
      - pyyaml
      - plyfile
      - open3d
